### ISSUE TITLE
In response to your Hacker News post

### ISSUE THREAD

**Issue by MikeRich88** [gadhra/php-barebones#1]
Wow, it is way too hard to just send someone a message these days. So we abuse other things just to try to send someone a helpful message.

I guess your post is too old to comment on anymore. Hopefully you eventually see this.

In reply to: https://news.ycombinator.com/item?id=36501596

You should just publish it as a Userscript instead to a site such as https://greasyfork.org/

How it works is, people can install one of a number of "Userscript managers" (https://en.wikipedia.org/wiki/Userscript_manager). These managers can run any arbitrary code on any page that the script defines. (Users still approve any new scripts added, etc. just like extensions)

There's other userscript repos as well, even an adult related one, so overall the Userscripts ecosystem is a lot more open.

That really sucks Mozilla would not just say what was wrong with your extension. My first thought would be to blame it on some kind of understaffing or something benign like that.

**Comment by gadhra** [comment]
Hey Mike!  I just wanted to say thank you, I really appreciate you reaching out - it means a lot.

I'm going to pursue the Userscript route, that's a great idea. I finally got Mozilla to accept my Add-On - I think I essentially didn't fill out the form correctly.  After the third resubmission I got a response that indicated I hadn't linked to the support area of my website, so once I just made sure that was blank I was good to go.

Anyway, I'm sure you're right - it's definitely something benign.  Just hella frustrating.  Appreciate you writing me back!
